export const FETCH_ALL_COMMENTS = "FETCH_ALL_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const NEWCHANGE_FALSE = "NEWCHANGE_FALSE";
export const TO_DELETE_ITEM = "TO_DELETE_ITEM";
